import { StyleSheet } from "react-native";
import Colors from "../../constants/Colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 25,
    backgroundColor: Colors.background,
    alignContent: "center",
  },
  containerHeader: {
    width: 200,
    height: "4%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 8,
  },
  image: {
    width: "25%",
    height: "100%",
    resizeMode: "contain",
    margin: 0,
    right: 10,
  },
  text: {
    marginVertical: 8,
    color: Colors.text,
    fontSize: 24,
    textAlign: "center",
    fontWeight: "400",
  },
  input: {
    width: 240,
    height: 45,
    backgroundColor: Colors.secondary,
    borderRadius: 32,
    borderColor: Colors.primary,
    borderWidth: 4,
    paddingStart: 15,
    color: Colors.background,
    fontWeight: "800",
    fontSize: 20,
    right: 10,
  },
  viewBtn: {
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 24,
  },
  btn: {
    height: 68,
    paddingHorizontal: 32,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
  },
  btnText: {
    fontSize: 24,
    color: Colors.text,
    fontWeight: "bold",
  },
  title: {
    textAlign: "center",
    color: Colors.text,
    fontSize: 36,
    fontWeight: "bold",
  },
  containerBtnBible: {
    marginBottom: 16,
  },
  containerBtn: {
    flexDirection: "row",
  },
  btnDeactivated: {
    width: 163,
    height: 119,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.secondaryOpacity65,
    borderRadius: 16,
    borderColor: Colors.primary,
    borderWidth: 4,
    marginHorizontal: 4,
  },
  textDeactivated: {
    color: Colors.background,
    fontSize: 24,
    fontWeight: "bold",
  },
  btnActivated: {
    width: 163,
    height: 119,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary,
    borderRadius: 16,
    borderColor: Colors.text,
    borderWidth: 4,
    marginHorizontal: 4,
  },
  textActivated: {
    color: Colors.text,
    fontSize: 24,
    fontWeight: "bold",
  },
  titleDinamic: {
    textAlign: "center",
    color: Colors.text,
    fontSize: 24,
    fontWeight: "bold",
  },
});
