import { StyleSheet } from "react-native";
import Colors from "../../constants/Colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 25,
    backgroundColor: Colors.background,
    alignContent: "center",
    paddingBottom: 50,
  },
  containerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  containerVersion: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.secondaryOpacity65,
    paddingHorizontal: 8,
    borderRadius: 12,
  },
  textVersion: {
    color: Colors.text,
    fontWeight: "bold",
    marginHorizontal: 3,
    fontSize: 16,
  },
  containerBookChapter: {
    alignItems: "center",
    marginVertical: 8,
  },
  nameBook: {
    color: Colors.text,
    fontWeight: "bold",
    marginHorizontal: 3,
    fontSize: 24,
    textTransform: "uppercase",
    marginBottom: 0,
  },
  numberChapter: {
    color: Colors.text,
    fontWeight: "bold",
    marginHorizontal: 3,
    fontSize: 96,
    bottom: 25,
    marginBottom: -40,
  },
  verseContainer: {
    paddingBottom: 10,
  },
  verseText: {
    color: Colors.text,
    fontSize: 18,
    textAlign: "center",
    fontWeight: "700",
  },
  fixedView: {
    width: "100%",
    height: 100,
    position: "absolute",
    bottom: 0.1,
    alignSelf: "center",
    backgroundColor: Colors.background,
    paddingVertical: 12,
    borderRadius: 8,
  },
  buttonText: {
    color: Colors.text,
    fontSize: 20,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  line: {
    height: 3,
    width: "100%",
    backgroundColor: Colors.secondary,
  },
  containerFooter: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  containerBtnFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "90%",
    height: 50,
    backgroundColor: Colors.secondaryOpacity65,
    paddingHorizontal: 10,
    borderRadius: 16,
    borderColor: Colors.primary,
    borderWidth: 4,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "80%",
    height: 300,
    marginHorizontal: "8%",
    paddingHorizontal: 16,
    backgroundColor: Colors.secondary,
    paddingTop: 8,
    paddingHorizontal: 10,
    borderRadius: 16,
    borderColor: Colors.primary,
    borderWidth: 4,
  },
  modalContainerHeader: {
    flexDirection: "row",
  },
  modalTitle: {
    width: "90%",
    fontWeight: "bold",
    marginHorizontal: 3,
    fontSize: 24,
    textAlign: "center",
    color: Colors.background,
  },
  closeButton: {
    width: "10%",
    textAlign: "right",
    alignItems: "center",
    justifyContent: "center",
  },
  modalContent: {
    marginTop: 16,
  },
  modalText: {
    height: 145,
    fontWeight: "bold",
    marginHorizontal: 3,
    fontSize: 16,
    textAlign: "center",
    color: Colors.background,
  },
  containerBtnAnnotation: {
    height: 75,
    marginTop: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  btnAnnotation: {
    width: 245,
    height: 50,
    backgroundColor: Colors.primary,
    paddingHorizontal: 10,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  modalBtnText: {
    color: Colors.text,
    fontWeight: "bold",
    marginHorizontal: 3,
    fontSize: 18,
  },
});
